/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakoutRoomUpdateManyWithoutRoomsInput } from "./BreakoutRoomUpdateManyWithoutRoomsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { MessageUpdateManyWithoutRoomsInput } from "./MessageUpdateManyWithoutRoomsInput";
import { PollUpdateManyWithoutRoomsInput } from "./PollUpdateManyWithoutRoomsInput";

@InputType()
class RoomUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BreakoutRoomUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => BreakoutRoomUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => BreakoutRoomUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  breakoutRooms?: BreakoutRoomUpdateManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  host?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPrivate?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MessageUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => MessageUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => MessageUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  messages?: MessageUpdateManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PollUpdateManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => PollUpdateManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => PollUpdateManyWithoutRoomsInput, {
    nullable: true,
  })
  polls?: PollUpdateManyWithoutRoomsInput;
}

export { RoomUpdateInput as RoomUpdateInput };
