/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakoutRoomCreateNestedManyWithoutRoomsInput } from "./BreakoutRoomCreateNestedManyWithoutRoomsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { MessageCreateNestedManyWithoutRoomsInput } from "./MessageCreateNestedManyWithoutRoomsInput";
import { PollCreateNestedManyWithoutRoomsInput } from "./PollCreateNestedManyWithoutRoomsInput";

@InputType()
class RoomCreateInput {
  @ApiProperty({
    required: false,
    type: () => BreakoutRoomCreateNestedManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => BreakoutRoomCreateNestedManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => BreakoutRoomCreateNestedManyWithoutRoomsInput, {
    nullable: true,
  })
  breakoutRooms?: BreakoutRoomCreateNestedManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  host?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPrivate?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutRoomsInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutRoomsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PollCreateNestedManyWithoutRoomsInput,
  })
  @ValidateNested()
  @Type(() => PollCreateNestedManyWithoutRoomsInput)
  @IsOptional()
  @Field(() => PollCreateNestedManyWithoutRoomsInput, {
    nullable: true,
  })
  polls?: PollCreateNestedManyWithoutRoomsInput;
}

export { RoomCreateInput as RoomCreateInput };
