/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BreakoutRoomListRelationFilter } from "../../breakoutRoom/base/BreakoutRoomListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MessageListRelationFilter } from "../../message/base/MessageListRelationFilter";
import { PollListRelationFilter } from "../../poll/base/PollListRelationFilter";

@InputType()
class RoomWhereInput {
  @ApiProperty({
    required: false,
    type: () => BreakoutRoomListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BreakoutRoomListRelationFilter)
  @IsOptional()
  @Field(() => BreakoutRoomListRelationFilter, {
    nullable: true,
  })
  breakoutRooms?: BreakoutRoomListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  host?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isPrivate?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MessageListRelationFilter)
  @IsOptional()
  @Field(() => MessageListRelationFilter, {
    nullable: true,
  })
  messages?: MessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PollListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PollListRelationFilter)
  @IsOptional()
  @Field(() => PollListRelationFilter, {
    nullable: true,
  })
  polls?: PollListRelationFilter;
}

export { RoomWhereInput as RoomWhereInput };
