/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoomService } from "../room.service";
import { RoomCreateInput } from "./RoomCreateInput";
import { Room } from "./Room";
import { RoomFindManyArgs } from "./RoomFindManyArgs";
import { RoomWhereUniqueInput } from "./RoomWhereUniqueInput";
import { RoomUpdateInput } from "./RoomUpdateInput";
import { BreakoutRoomFindManyArgs } from "../../breakoutRoom/base/BreakoutRoomFindManyArgs";
import { BreakoutRoom } from "../../breakoutRoom/base/BreakoutRoom";
import { BreakoutRoomWhereUniqueInput } from "../../breakoutRoom/base/BreakoutRoomWhereUniqueInput";

export class RoomControllerBase {
  constructor(protected readonly service: RoomService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Room })
  async createRoom(@common.Body() data: RoomCreateInput): Promise<Room> {
    return await this.service.createRoom({
      data: data,
      select: {
        active: true,
        createdAt: true,
        createdBy: true,
        creator: true,
        id: true,
        isActive: true,
        name: true,
        roomId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Room] })
  @ApiNestedQuery(RoomFindManyArgs)
  async rooms(@common.Req() request: Request): Promise<Room[]> {
    const args = plainToClass(RoomFindManyArgs, request.query);
    return this.service.rooms({
      ...args,
      select: {
        active: true,
        createdAt: true,
        createdBy: true,
        creator: true,
        id: true,
        isActive: true,
        name: true,
        roomId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async room(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    const result = await this.service.room({
      where: params,
      select: {
        active: true,
        createdAt: true,
        createdBy: true,
        creator: true,
        id: true,
        isActive: true,
        name: true,
        roomId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRoom(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() data: RoomUpdateInput
  ): Promise<Room | null> {
    try {
      return await this.service.updateRoom({
        where: params,
        data: data,
        select: {
          active: true,
          createdAt: true,
          createdBy: true,
          creator: true,
          id: true,
          isActive: true,
          name: true,
          roomId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRoom(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    try {
      return await this.service.deleteRoom({
        where: params,
        select: {
          active: true,
          createdAt: true,
          createdBy: true,
          creator: true,
          id: true,
          isActive: true,
          name: true,
          roomId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/breakoutRooms")
  @ApiNestedQuery(BreakoutRoomFindManyArgs)
  async findBreakoutRooms(
    @common.Req() request: Request,
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<BreakoutRoom[]> {
    const query = plainToClass(BreakoutRoomFindManyArgs, request.query);
    const results = await this.service.findBreakoutRooms(params.id, {
      ...query,
      select: {
        active: true,
        createdAt: true,
        creator: true,
        id: true,
        name: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/breakoutRooms")
  async connectBreakoutRooms(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: BreakoutRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      breakoutRooms: {
        connect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/breakoutRooms")
  async updateBreakoutRooms(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: BreakoutRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      breakoutRooms: {
        set: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/breakoutRooms")
  async disconnectBreakoutRooms(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: BreakoutRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      breakoutRooms: {
        disconnect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }
}
