/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { BreakoutRoom } from "./BreakoutRoom";
import { BreakoutRoomCountArgs } from "./BreakoutRoomCountArgs";
import { BreakoutRoomFindManyArgs } from "./BreakoutRoomFindManyArgs";
import { BreakoutRoomFindUniqueArgs } from "./BreakoutRoomFindUniqueArgs";
import { CreateBreakoutRoomArgs } from "./CreateBreakoutRoomArgs";
import { UpdateBreakoutRoomArgs } from "./UpdateBreakoutRoomArgs";
import { DeleteBreakoutRoomArgs } from "./DeleteBreakoutRoomArgs";
import { Room } from "../../room/base/Room";
import { BreakoutRoomService } from "../breakoutRoom.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BreakoutRoom)
export class BreakoutRoomResolverBase {
  constructor(
    protected readonly service: BreakoutRoomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "read",
    possession: "any",
  })
  async _breakoutRoomsMeta(
    @graphql.Args() args: BreakoutRoomCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BreakoutRoom])
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "read",
    possession: "any",
  })
  async breakoutRooms(
    @graphql.Args() args: BreakoutRoomFindManyArgs
  ): Promise<BreakoutRoom[]> {
    return this.service.breakoutRooms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BreakoutRoom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "read",
    possession: "own",
  })
  async breakoutRoom(
    @graphql.Args() args: BreakoutRoomFindUniqueArgs
  ): Promise<BreakoutRoom | null> {
    const result = await this.service.breakoutRoom(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BreakoutRoom)
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "create",
    possession: "any",
  })
  async createBreakoutRoom(
    @graphql.Args() args: CreateBreakoutRoomArgs
  ): Promise<BreakoutRoom> {
    return await this.service.createBreakoutRoom({
      ...args,
      data: {
        ...args.data,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BreakoutRoom)
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "update",
    possession: "any",
  })
  async updateBreakoutRoom(
    @graphql.Args() args: UpdateBreakoutRoomArgs
  ): Promise<BreakoutRoom | null> {
    try {
      return await this.service.updateBreakoutRoom({
        ...args,
        data: {
          ...args.data,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BreakoutRoom)
  @nestAccessControl.UseRoles({
    resource: "BreakoutRoom",
    action: "delete",
    possession: "any",
  })
  async deleteBreakoutRoom(
    @graphql.Args() args: DeleteBreakoutRoomArgs
  ): Promise<BreakoutRoom | null> {
    try {
      return await this.service.deleteBreakoutRoom(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "any",
  })
  async getRoom(@graphql.Parent() parent: BreakoutRoom): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
