/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Poll as PrismaPoll } from "@prisma/client";

export class PollServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PollCountArgs, "select">): Promise<number> {
    return this.prisma.poll.count(args);
  }

  async polls(args: Prisma.PollFindManyArgs): Promise<PrismaPoll[]> {
    return this.prisma.poll.findMany(args);
  }
  async poll(args: Prisma.PollFindUniqueArgs): Promise<PrismaPoll | null> {
    return this.prisma.poll.findUnique(args);
  }
  async createPoll(args: Prisma.PollCreateArgs): Promise<PrismaPoll> {
    return this.prisma.poll.create(args);
  }
  async updatePoll(args: Prisma.PollUpdateArgs): Promise<PrismaPoll> {
    return this.prisma.poll.update(args);
  }
  async deletePoll(args: Prisma.PollDeleteArgs): Promise<PrismaPoll> {
    return this.prisma.poll.delete(args);
  }
}
