/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Poll } from "./Poll";
import { PollCountArgs } from "./PollCountArgs";
import { PollFindManyArgs } from "./PollFindManyArgs";
import { PollFindUniqueArgs } from "./PollFindUniqueArgs";
import { CreatePollArgs } from "./CreatePollArgs";
import { UpdatePollArgs } from "./UpdatePollArgs";
import { DeletePollArgs } from "./DeletePollArgs";
import { OptionFindManyArgs } from "../../option/base/OptionFindManyArgs";
import { Option } from "../../option/base/Option";
import { Room } from "../../room/base/Room";
import { PollService } from "../poll.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Poll)
export class PollResolverBase {
  constructor(
    protected readonly service: PollService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "any",
  })
  async _pollsMeta(
    @graphql.Args() args: PollCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Poll])
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "any",
  })
  async polls(@graphql.Args() args: PollFindManyArgs): Promise<Poll[]> {
    return this.service.polls(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Poll, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "read",
    possession: "own",
  })
  async poll(@graphql.Args() args: PollFindUniqueArgs): Promise<Poll | null> {
    const result = await this.service.poll(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "create",
    possession: "any",
  })
  async createPoll(@graphql.Args() args: CreatePollArgs): Promise<Poll> {
    return await this.service.createPoll({
      ...args,
      data: {
        ...args.data,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "update",
    possession: "any",
  })
  async updatePoll(@graphql.Args() args: UpdatePollArgs): Promise<Poll | null> {
    try {
      return await this.service.updatePoll({
        ...args,
        data: {
          ...args.data,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Poll)
  @nestAccessControl.UseRoles({
    resource: "Poll",
    action: "delete",
    possession: "any",
  })
  async deletePoll(@graphql.Args() args: DeletePollArgs): Promise<Poll | null> {
    try {
      return await this.service.deletePoll(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Option], { name: "options" })
  @nestAccessControl.UseRoles({
    resource: "Option",
    action: "read",
    possession: "any",
  })
  async findOptions(
    @graphql.Parent() parent: Poll,
    @graphql.Args() args: OptionFindManyArgs
  ): Promise<Option[]> {
    const results = await this.service.findOptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  @nestAccessControl.UseRoles({
    resource: "Room",
    action: "read",
    possession: "any",
  })
  async getRoom(@graphql.Parent() parent: Poll): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
