/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PollService } from "../poll.service";
import { PollCreateInput } from "./PollCreateInput";
import { Poll } from "./Poll";
import { PollFindManyArgs } from "./PollFindManyArgs";
import { PollWhereUniqueInput } from "./PollWhereUniqueInput";
import { PollUpdateInput } from "./PollUpdateInput";

export class PollControllerBase {
  constructor(protected readonly service: PollService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Poll })
  async createPoll(@common.Body() data: PollCreateInput): Promise<Poll> {
    return await this.service.createPoll({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Poll] })
  @ApiNestedQuery(PollFindManyArgs)
  async polls(@common.Req() request: Request): Promise<Poll[]> {
    const args = plainToClass(PollFindManyArgs, request.query);
    return this.service.polls({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async poll(
    @common.Param() params: PollWhereUniqueInput
  ): Promise<Poll | null> {
    const result = await this.service.poll({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePoll(
    @common.Param() params: PollWhereUniqueInput,
    @common.Body() data: PollUpdateInput
  ): Promise<Poll | null> {
    try {
      return await this.service.updatePoll({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Poll })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePoll(
    @common.Param() params: PollWhereUniqueInput
  ): Promise<Poll | null> {
    try {
      return await this.service.deletePoll({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
